---

- name: Check Subscription Status
  shell: LANG=C subscription-manager list | awk  ' ( $1 == "Status:" ) { print $2 } ' | sort -u
  register: subscription_status

- name: make sure registration credentials are provided
  fail:
    msg: "please provide registration credentials for this system"
  when: ( subscription_status.stdout != "Subscribed" ) and ( (reg_activation_key is not defined) or (reg_organization_id is not defined) )
  #when: (reg_activation_key is not defined) or (reg_organization_id is not defined) or (reg_sub_name is not defined)

- name: Installing credentials for Satellite 6 server  "{{ satellite_server }}"
  yum:
    name: "{{ 'https://' +  satellite_server +'/pub/katello-ca-consumer-latest.noarch.rpm' }}"
    state: present
    validate_certs: no
  when: not( (satellite_server is undefined) or (satellite_server is none) or (satellite_server | trim == '') )

- name: ensure system is registered using known activation key
  redhat_subscription:
    activationkey: "{{ reg_activation_key }}"
    org_id: "{{ reg_organization_id }}"
    # pool: "{{ reg_sub_name }}"
    state: present
  when: ( subscription_status.stdout != "Subscribed" )

- name: Reset all previous repositories
  shell: |
    subscription-manager repos --disable="*"
    num=0
    for r in /etc/yum.repos.d/*.repo; do
      num=$(( num + $(grep  -c "^enabled.*=.*1$" $r) ))
      sed -i 's/^enabled.*=.*1/enabled = 0/g' $r
    done
    echo "$num"
  register: repo_cleanup
  changed_when: repo_cleanup.stdout > 0
  failed_when: repo_cleanup.rc > 0
  when: force_repo_reset

# TODO: Change functionality to use yum module
- name: check repositories system has access to
  shell: yum repolist warn=no
  register: repolist
...
