---

- name: Enable Debugging
  debug:
    verbosity: "{{ debuglevel }}"

- name: check default gateway
  shell: route -n
  register: route

- name: set default gateway
  shell: route add default gw 192.168.0.2
  when: ( ansible_default_ipv4.gateway != "192.168.0.2" )

- include: ./system-registration-part1.yml
  when: check_repos
- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/system-registration.yml' }}"
  when: check_repos
  tags:
    - osprep
    - system-registration

- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/package-installation.yml' }}"
  tags:
    - osprep
    - packages
- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/service-configuration.yml' }}"
  tags:
    - osprep
    - services
- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/system-tuning.yml' }}"
  tags:
    - osprep
    - system-tuning

- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/check-hostname-dns.yml' }}"
  tags:
    - osprep
    - set-hostname

- include: ./disk-partitioning.yml
  when: 
    - disk_partitioning
  tags:
    - osprep
    - disk_partitioning

- include: ./sap-check-media.yml
  tags:
    - hana-install
    - media-check

- include: ./sap-hana-install.yml
  tags:
    - hana-install

...
