---

- name: Create File for Scale-Out Enviornments
  template:
    src: deployment_install_hana_SID.conf.j2
    dest: /usr/local/bin/install_hana_{{ item.value.hana_sid|lower }}.conf
    mode: 0755
  with_dict: "{{ instances }}"

# Generate Template under Linux
# ./hdbinst --dump_configfile_template=/tmp/test.cfg
- name: copy installation answer file
  template: src=deployment_hana_inst_SID.cfg.j2 dest=/tmp/hana_install_{{ item.value.hana_sid|lower}}.cfg
  with_dict: "{{ instances }}"

- name: create usr sap directory
  file:
    path: "/usr/sap/{{ item.value.hana_sid|upper }}"
    state: directory
  with_dict: "{{ instances }}"

- name: create hana shared directory
  file:
    path: "/hana/shared/{{ item.value.hana_sid|upper }}"
    state: directory
  with_dict: "{{ instances }}"

- name: create hana data directory
  file:
    path: "/hana/data/{{ item.value.hana_sid|upper }}"
    state: directory
  with_dict: "{{ instances }}"

- name: create hana log directory
  file:
    path: "/hana/log/{{ item.value.hana_sid|upper }}"
    state: directory
  with_dict: "{{ instances }}"

- name: create sap sid group
  group: name={{ item.value.hana_sid|lower }}shm gid={{ item.value.id_group_shm }}
  with_dict: "{{ instances }}"

- name: create sap sid user
  user:
    name: "{{ item.value.hana_sid|lower }}adm"
    uid: "{{ item.value.id_user_sidadm }}"
    group: "sapsys"
    groups: "{{ item.value.hana_sid|lower }}shm"
    home: "/usr/sap/{{ item.value.hana_sid|upper }}/home"
    password: "{{ item.value.pw_user_sidadm|password_hash('sha512') }}"
  with_dict: "{{ instances }}"

# 20170513 Thomas Bludau
# Very complicated part. Could be different on every enviornment.

#- name: copy global.ini
#  copy: src=global.ini dest=/hana/shared/{{ item.value.hana_sid|upper }}/global.ini
#  with_dict: "{{ instances }}"

# Only Start when:
# Hostname Resolution is fine!
# Instance-Hostname is existing and configured
# Updates are Installed
# System rebooted (Problems otherwise, while f.e. mounting nfs)
# Systems already configured (preconfigure)
# Every System in the Scale-Out Enviornment is ready
# Only Execute on One System in Scale-Out Enviornment

- name: execute unattended installation (logfile /var/log/hana_install.log )
  shell: ./hdblcm --configfile=/tmp/hana_install_{{ item.value.hana_sid|lower}}.cfg -b --remote_execution=saphostagent >> /var/log/hana_install_{{ item.value.hana_sid|lower}}.log
  args:
    chdir: "{{ hana_installdir }}/DATA_UNITS/HDB_SERVER_LINUX_{{ ansible_architecture|upper }}/"
    creates: "/usr/sap/{{ item.value.hana_sid|upper }}/HDB{{ item.value.hana_instance_number }}/exe/hdbdaemon"
  with_dict: "{{ instances }}"
  when: deployment_instance is defined
  
# ########### ANDBUICK 2017-07-27
# additional information about the "hdblcm"-tool
# from SAP HANA Administration Guide / SAP HANA 2.0 Vers.01 2016-11-30# 
# & SAP HANA Server Installation Guide / SAP HANA 2.0 Vers. 01 2017-04-12
# & SAP NOTE 2078425 #19 / 2016-06-17
#
# The SAP HANA database lifecycle manager (HDBLCM) is used to install, update, or configure an SAP HANA system. 
# You can use the SAP HANA database lifecycle manager in graphical user, command-line, or Web user interface
# "Batch-mode" can only be performed in commandline mode.
# The SAP HANA database lifecycle manager is available in two varieties - an installation medium version to perform installation and update, and a resident version
# for update and configuration that is unpacked on the SAP HANA host during installation or update.
# Every time you install or update an SAP HANA system, you can be sure that any subsequent configuration tasks performed with the SAP HANA database lifecycle manager
# will work as expected because the installation or update tool and the configuration tool are of the same version and have been tested together. The SAP HANA resident 
# HDBLCM is located at <sapmnt>/<SID>/hdblcm.
#
# ./hdblcm --batch --configfile=/var/tmp/<SID>_configfile
#
# When using batch mode, passwords must either be defined in the configuration file, or passed to the installer using an XML password file and streamed in via standard 
# input. In both cases, it is necessary to prepare the passwords.
# To execute tasks as the system administrator use user <SID>adm.
#
# If parameters are specified in the command line, they override the corresponding parameters in the configuration file. Parameters in the configuration file override default settings. 
# Order of parameter precedence: Command Line > Configuration File > Default
#
# SAP HANA resident HDBLCM directory: 
# cd <sapmnt>/<SID>/hdblcm 
# Start the SAP HANA platform lifecycle management tool:
# ./hdblcm --batch <additional parameters>
# or
# ./hdblcm -b <additional parameters>
# It is mandatory to provide an SAP HANA system ID (SID) and user passwords during installation. 
# In batch mode, you are restricted to providing these parameter values as call options on the command line (for
# passwords, by means of an XML file) or in a configuration file. If you don't provide parameter values for the
# other required parameters, you implicitly accept the default values.
#
# ########### Parameter reference (only selection) 
# -- see: SAP HANA Server & Installation Guide SAP HANA 2.0 / Vers. 01 
#
# (action)
# #####
# The default for this parameter is --action=exit
# --action[=extract_components|install|update]
#
# (addhosts)
# #####
# Specifies additional hosts for the SAP HANA system as a comma-separated list. Individual host options are specified by a colon-separated list.
# This parameter is used when configuring a multiple-host system during installation.
# If the root user has a user name other than "root", the root_user parameter must also be specified in combination with addhosts.
#
# The action parameter must be specified in combination with addhosts.
# --addhosts=<host>[,<host2>]
# where the <host> syntax is as follows:
# <host_name>[:role=worker|standby|extended_storage_worker|
# extended_storage_standby| ets_worker|ets_standby|streaming|rdsync|
# xs_worker|xs_standby][:group=<name>][:storage_partition=<number>] 
#
# worker - A worker host (default) is used for database processing.
# workergroup - Specifies the worker group of the host. If undefined, the worker group is named "default".
# 
# extended_storage_worker - Worker host for SAP HANA dynamic tiering
# extended_storage_standby - Standby host for SAP HANA dynamic tiering
# ets_worker - Worker host for SAP HANA accelerator for SAP ASE
# ets_standby - Standby host for SAP HANA accelerator for SAP ASE
# group - Specifies the host group ID for failover scenarios. If undefined, the host group is named "default" 
# rdsync - Host for SAP HANA remote data sync# standby - A standby host is idle and available for failover in a high-availability environment.
# streaming - Host for SAP HANA smart data streaming
# storage_partition - Specifies the storage partition number, which is a logical role number assigned to non-shared storage devices in a storage connector API.
# Standby hosts do not have a storage partition.
# 
# xs_worker - Host for SAP HANA XS advanced runtime
# xs_standby - Standby host for SAP HANA XS advanced runtime
# 
#
# (add_local_roles)
# ###### 
# Specifies additional roles of the local host during SAP HANA system installation. Multiple host roles are not supported in production environments. 
# However, if XS advanced runtime is installed, hosts can share multiple roles.
# --add_local_roles=<role1>[,<role2>]
# 
# (add_roles)
# #####
# Specifies additional roles for exisiting SAP HANA hosts during SAP HANA option installation. Multiple host roles are not supported in production environments. 
# However, if XS advanced runtime is installed, hosts can share multiple roles.
# --add_roles=<host name>=<role> -R <host name>=<role>
#
# (autostart)
# #####
# Restarts system after machine reboot. where 0 = off, and 1 = on. The default for this parameter is --autostart=0 (off).
# --autostart=[0|1]
#
# (basepath_streaming)
# #####
# Specifies the location of streaming logstores and runtime information. The default for this parameter is --basepath_streaming=/hana/data_streaming/<SID>.
# --basepath_streaming=<location of streaming logstores and runtime information>
#
# (batch)
# #####
# Runs the SAP HANA lifecycle management tool from the command line in batch mode using default values for unspecified parameters. 
# If mandatory values are omitted or if invalid values are specified, the program issues an error message.
# short form is
# -b
#
# (check_installation)
# #####
# Checks the SAP HANA installation# --action=check_installation
#
# 
# (client_path)
# #####
# Specifies the installation path for the client.
# --client_path=<path for client installation>
#
#
# (configfile)
# #####
# Loads a configuration file of call option key-value pairs to be passed to the SAP HANA lifecycle management program
# --configfile=<file path>
#
# (create_initial_tenant)
# #####
# The default for this parameter is --create_initial_tenant (on)
# --create_initial_tenant[=off]
#
#
# (dump_configfile_template)
# #####
# Specifies a file path to which a template configuration file is exported. The call options in the template configuration file are set to their default values, 
# and can be edited.
# --dump_configfile_template=<file path>
#
# 
# (hostname)
# #####
# Specifies the virtual host name of the system host
# --hostname=<name of the host machine>
# short form is
# -H
#
# (ignore)
# #####
# Specifies failing preequisite checks that the SAP HANA platform lifecycle management tools should ignore.
# --ignore=<check1>[,<check2>]...
#
# (install_hostagent)
# #####
# Enables the installation or update of the SAP host agent. The default for this parameter is --install_hostagent (on).
# --install_hostagent[=off]
#
# (logpath)
# #####
# Specifies the path to the log directory of the SAP HANA system. The default for this parameter is --logpath=/hana/log/<SID>.
# --logpath=<path to log directory>
# 
# (max_mem)
# #####
# Specifies the maximum memory allocation for a new system in MB.This parameter must be used in combination with restrict_max_mem. The default for this parameter is --max_mem=0.
# --max_mem=<MB>
#
# (nostart_tenant_db)
# #####
# Prevents the SAP HANA tenant databases from being started.# --nostart_tenant_db
#
# 
# (number)
# Specifies the instance number of the SAP HANA system.
# #####
# --number=<instance number>
# short form is
# -n
#
# (read_password_from_stdin)
# #####
# Reads passwords in XML syntax via input stream in batch mode. When using read_password_from_stdin in batch mode, the program looks for the
# necessary passwords from an input stream. Therefore, the following two requirements apply: A text file with XML tagging is created before calling the# read_password_from_stdin parameter during installation.And Batch mode is specified from the command line.
# --read_password_from_stdin=xml
#
# (sapmnt)
# #####
# Specifies the path to the SAP mount directory, which can be used as a shared directory between multiple hosts.
# --sapmnt=<installation path>
#
# (sid)
# #####
# Specifies a system ID. The SAP system ID (SID) is the identifier for the SAP HANA system.
# The ID must be unique throughout your organization and consistent throughout your SAP system installation landscape
# If you want to install an additional application server instance, make sure that no gateway instance with the same SAP SID exists in your SAP system landscape.
# --sid=<SID>
# short form is
# -s
#
# (sld_hostname)
# #####
# Specifies the name of the host where the SLD system is installed.
# --sld_hostname=<host name>
#
# (storage_cfg)
# #####
# Specifies a location where a global.ini is defined. It is possible to set up a storage connector, allowing SAP HANA to use hardware vendor-specific scripts for automated resource allocation 
# and input/output fencing during failover.Resource allocation scripts are dependent on the hardware used. Therefore, only the hardware partners can provide correct scripts.
# --storage_cfg=<directory of the storage configuration>
#
#
# (system_usage)
# #####
# Specifies the usage type of the system to be installed. This setting is stored in the global.ini file, and can be used to identify the intended usage of the system.The default for this parameter is --system_usage=custom.
# --system_usage=[production|test|development|custom]
#
#Â (vm)
# #####
# Specifies the path of the Java runtime file. This parameter is only relevant if the SAP HANA studio is selected for installation or update.
# --vm=<Java path>
#
#
# ################################### 





...
